// export const routes = [
//   {
//     path: "/",
//     label: "Dashboard",
//     icon: "Home",
//     showInSidebar: false,
//     order: 0,
//   },
//   {
//     path: "/logs",
//     label: "Logs",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 2,
//   },
//   {
//     path: "/business-loans",
//     label: "Business Loans",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 2,
//   },
//   {
//     path: "/mv-ivr-logs",
//     label: "MV IVR Logs",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 3,
//   },
//   {
//     path: "/cr-zype-success-leads",
//     label: "CR Zype success Leads",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 4,
//   }
// ];


// src/routes/routes.js
export const routes = [
  {
    path: "/",
    label: "Dashboard",
    icon: "Home",
    showInSidebar: false,
    order: 0,
    roles: ["admin", "super-admin", "kb-admin", "kb-mumbai", "kb-banglore", "mv-admin"],
  },
  {
    path: "/logs",
    label: "Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 2,
    roles: ["super-admin", "mv-admin"],
  },
  {
    path: "/business-loans",
    label: "Business Loans",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 3,
    roles: ["super-admin"],
  },
  {
    path: "/mv-ivr-logs",
    label: "MV IVR Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 4,
    roles: ["admin", "super-admin"],
  },
  {
    path: "/cr-zype-success-leads",
    label: "CR Zype Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 5,
    roles: ["super-admin"],
  },
  {
    path: "/kb-success-leads",
    label: "KB Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 6,
    roles: ["super-admin", "kb-admin"],
  },
  // {
  //   path: "/kb-mumbai-success-leads",
  //   label: "KB Logs - Mumbai",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 7,
  //   roles: ["super-admin", "kb-mumbai"],
  // },
  // {
  //   path: "/kb-banglore-success-leads",
  //   label: "KB Logs - Banglore",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 8,
  //   roles: ["super-admin", "kb-banglore"],
  // },
  {
    path: "/offer-leads",
    label: "Offer Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 9,
    roles: ["super-admin", "mv-page"],
  },
  {
    path: "/selected-lenders",
    label: "Selected Lenders",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 10,
    roles: ["super-admin", "mv-page"],
  }
];