// export const routes = [
//   {
//     path: "/",
//     label: "Dashboard",
//     icon: "Home",
//     showInSidebar: false,
//     order: 0,
//   },
//   {
//     path: "/logs",
//     label: "Logs",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 2,
//   },
//   {
//     path: "/business-loans",
//     label: "Business Loans",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 2,
//   },
//   {
//     path: "/mv-ivr-logs",
//     label: "MV IVR Logs",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 3,
//   },
//   {
//     path: "/cr-zype-success-leads",
//     label: "CR Zype success Leads",
//     icon: "ClipboardList", 
//     showInSidebar: true,
//     group: "Lead Management",
//     groupOrder: 1, 
//     order: 4,
//   }
// ];


// src/routes/routes.js
export const routes = [
  {
    path: "/",
    label: "Dashboard",
    icon: "Home",
    showInSidebar: false,
    order: 0,
    roles: ["admin", "super-admin", "kb-admin", "kb-mumbai", "kb-banglore", "mv-admin", "management"],
  },
  {
    path: "/logs",
    label: "Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 2,
    roles: ["super-admin", "mv-admin"],
  },
  {
    path: "/business-loans",
    label: "Business Loans",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 3,
    roles: ["super-admin"],
  },
  {
    path: "/mv-ivr-logs",
    label: "MV IVR Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 4,
    roles: ["admin", "super-admin", "management"],
  },
  {
    path: "/cr-zype-success-leads",
    label: "CR Zype Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 5,
    roles: ["super-admin"],
  },
  {
    path: "/kb-success-leads",
    label: "KB Logs",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Lead Management",
    groupOrder: 1,
    order: 6,
    roles: ["super-admin", "kb-admin", "management"],
  },
  // {
  //   path: "/kb-mumbai-success-leads",
  //   label: "KB Logs - Mumbai",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 7,
  //   roles: ["super-admin", "kb-mumbai"],
  // },
  // {
  //   path: "/kb-banglore-success-leads",
  //   label: "KB Logs - Banglore",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 8,
  //   roles: ["super-admin", "kb-banglore"],
  // },

  {
    path: "/offer-leads-analytics",
    label: "High Analytics Dashboard",
    icon: "Home",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 8,
    roles: ["super-admin", "mv-page-admin", "management"],
  },
  {
    path: "/disbursal-dashboard",
    label: "Disbursal Dashboard",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 8.5,
    roles: ["super-admin", "mv-page-admin", "management"],
  },
  {
    path: "/offer-leads",
    label: "High Offer Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 9,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/selected-lenders",
    label: "High Selected Lenders",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 10,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management"],
  },
    {
    path: "/kb-lending-page",
    label: "High KB Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 11,
    roles: ["super-admin", "kb-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/mv-success-leads",
    label: "High MV Success Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 11.5,
    roles: ["super-admin", "mv-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/draft-leads-new",
    label: "High Draft Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 12,
    roles: ["super-admin", "mv-page", "mv-page-admin", "management"],
  },
  {
    path: "/short-offer-leads-analytics",
    label: "Short Analytics Dashboard",
    icon: "Home",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 19,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-disbursal-dashboard",
    label: "Disbursal Dashboard",
    icon: "TrendingUp",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 19.5,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-offer-leads",
    label: "Short Offer Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 20,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-selected-lenders",
    label: "Short Selected Lenders",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 21,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-draft-leads",
    label: "Short Draft Leads",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 22,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  {
    path: "/short-user-track",
    label: "Short User Track",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "Short Ticket",
    groupOrder: 2,
    order: 23,
    roles: ["super-admin", "short-page-admin", "management"],
  },
  // {
  //   path: "/short-kb-lending-page",
  //   label: "Short KB Success Leads",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Short Ticket",
  //   groupOrder: 2,
  //   order: 24,
  //   roles: ["super-admin", "kb-admin", "short-page-admin", "management"],
  // },
  // {
  //   path: "/lending-user-journey",
  //   label: "Lending User Journey",
  //   icon: "ClipboardList",
  //   showInSidebar: true,
  //   group: "Lead Management",
  //   groupOrder: 1,
  //   order: 13,
  //   roles: ["super-admin", "mv-page", "mv-page-admin", "mv-admin"],
  // },
  {
    path: "/user-track",
    label: "High User Track",
    icon: "ClipboardList",
    showInSidebar: true,
    group: "High Ticket",
    groupOrder: 1.5,
    order: 14,
    roles: ["super-admin", "mv-page", "mv-page-admin", "mv-admin", "management"],
  },
  {
    path: "/otp-logs",
    label: "OTP Logs",
    icon: "ShieldCheck",
    showInSidebar: true,
    group: "Security",
    groupOrder: 3,
    order: 30,
    roles: ["super-admin"],
  },
  {
    path: "/export-audit-logs",
    label: "Export Logs",
    icon: "FileDown",
    showInSidebar: true,
    group: "Security",
    groupOrder: 3,
    order: 31,
    roles: ["super-admin"],
  },
];